# installer Proftp

- name: Installation des paquets serveur ftp
  apt: name={{ item }} state=present
  with_items:
   - proftpd-basic
   - proftpd-mod-mysql

# ******** penser à lineinfile pour configurer simplement quelques lignes dans le fichier de conf.
- name: Modification du fichier proftpd.conf
  lineinfile: dest=/etc/proftpd/proftpd.conf backup=yes line="DefaultRoot ~"

#- name : Copier un exemple de configuration php5-fpm pour limiter openbasedir 
#  copy: src=phpfpm/conf.example dest=/etc/php5/fpm/pool.d/
#
#- name : Copier commun.conf pour nginx
#  copy: src=nginx/commun.conf dest=/etc/nginx/
#
#- name: Création des dossiers utiles
#  file: dest={{item}} state=directory recurse=yes owner=www-data group=www-data
#  with_items:
#    - /home/web/
#
#- service: name=nginx state=started
