---
 
- name: Installation de Monit
  file: dest={{item}} state=directory recurse=yes
  with_items:
    - /usr/local/bin/utilserv/firewall
    - /etc/firewall/conf.d/

#- copy: src={{ item }} dest=/etc/firewall/conf.d/ mode=0600
#  with_fileglob:
#  - ./conf.d/*

- copy: src={{ item }} dest=/usr/local/bin/utilserv/firewall/ group=staff mode=0755
  with_fileglob:
  - ./bin/*


- service: name=monit enabled=yes state=started
